version: "3.9"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: invest
      POSTGRES_PASSWORD: investpw
      POSTGRES_DB: investdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: ./backend
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://invest:investpw@db/investdb
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: supersecret
      ACCESS_TOKEN_EXPIRE_MINUTES: 480
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    restart: unless-stopped

volumes:
  db_data:
